/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NavigatorView: typeof import('./../src/components/NavigatorView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulerMeasure: typeof import('./../src/components/RulerMeasure.vue')['default']
    SlideListPanel: typeof import('./../src/components/SlideListPanel.vue')['default']
  }
}
